Error-checks and bug-fixes.

diff --git a/request_and_compare b/request_and_compare
--- a/request_and_compare
+++ b/request_and_compare
@@ -62,9 +62,14 @@ crlf_to_lf() {
 
 # Generate the expected response by for later comparison with a response from server and add it to input file.
 generate_expected_response() {
-    local remaining_segments=$(cat "${1}")
+    local remaining_segments=$(cat "${1}" 2>/dev/null)
     if [ -z "${remaining_segments}" ]; then
-        return 1
+        echo "${DELIM}" > "${1}"
+        echo "${DELIM}" > "${1}"
+        echo "${DELIM}" > "${1}"
+        echo "${DELIM}" > "${1}"
+        echo -e "${COLOR_RED}Generated an empty file. You have to fill this in according to the -h|--help section!${COLOR_RESET}"
+        return 0
     fi
     local current_segment
     local response
@@ -74,6 +79,7 @@ generate_expected_response() {
     current_segment=$(get_current_segment "${remaining_segments}")
     response=$(get_response "${current_segment}")
     if [ -z "${response}" ]; then
+        echo -e "${COLOR_RED}Server failed to respond.${COLOR_RESET}"
         return 1
     fi
 
@@ -85,7 +91,7 @@ generate_expected_response() {
 
     # Check that there isn't an expected response segment already
     if [ "$(tail -n 2 "${1}" | head -n 1)" != "${DELIM}" ]; then
-        echo -e "\033[1mProvided files already contains an expected response segment.
+        echo -e "\033[1mProvided files is either malformed or already contains an expected response segment.
 If you want to generate a new one, please remove this segment as in the example below:\033[m
 GET_TEST
 ################################
@@ -105,6 +111,7 @@ ETag
     sed -i '$d' "${1}"
     echo "${response}" >> "${1}"
     echo "${DELIM}" >> "${1}"
+    echo -e "Request response generated and added to file!"
 }
 
 # Main function of the script.
@@ -126,6 +133,7 @@ run() {
     current_segment=$(get_current_segment "${remaining_segments}")
     response=$(get_response "${current_segment}")
     if [ -z "${response}" ]; then
+        echo -e "${COLOR_RED}Server failed to respond.${COLOR_RESET}"
         return 1
     fi
 
@@ -156,8 +164,8 @@ run() {
 run_loop() {
     echo -e "\033[1m===== New run at $(date +%r) =====\033[m"
     for file in "${@}"; do
-        run "${file}"
-        if [ $? -ne 0 ]; then
+        if run "${file}"; then
+
             return 1
         fi
     done
@@ -233,9 +241,7 @@ Server: lighttpd/1.4.55
 fi
 
 if [ "${1}" == "-g" ]; then
-    if generate_expected_response "${2}"; then
-        echo -e "Request response generated and added to file!"
-    else
+    if ! generate_expected_response "${2}"; then
         echo -e "${COLOR_RED}Failed to generate request file. Either bad input file or no response from server!${COLOR_RESET}"
         exit 1
     fi
